server {
    listen 80;
    server_name localhost aula.dev aula.127.0.0.1.sslip.io;

    location / {
        proxy_pass http://app:3000; # Substitua "app" pelo nome do serviço do seu aplicativo no Docker Compose
    }
}