#docker comopose exec nginx nginx -s reload

server {
    listen 80;

    # _ é um curinga que corresponde a qualquer nome de host, garantindo que o Nginx responda a todas as solicitações, independentemente do nome de domínio usado. Isso é útil em ambientes de produção onde o nome de
    server_name _;
    return 301 https://$host$request_uri; # Redireciona todas as solicitações HTTP para HTTPS
}

server {
    listen 443 ssl;
    server_name _; # Responde a todas as solicitações HTTPS

    ssl_certificate /etc/nginx/certs/cert.pem; # Substitua pelo caminho do seu certificado SSL
    ssl_certificate_key /etc/nginx/certs/key.pem; # Substitua pelo caminho da sua chave SSL
    ssl_protocols TLSv1.2 TLSv1.3; # Habilita apenas protocolos seguros

    location / {
        proxy_pass http://app:3000; # Substitua "app" pelo nome do serviço do seu aplicativo no Docker Compose
    }
}